# Copyright 2026-present Coinbase Global, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Generate dataclass models from the Prime OpenAPI specification."""

from __future__ import annotations

import json
import re
import textwrap
from collections import defaultdict
from pathlib import Path
from typing import Any

import yaml
from model_config import (
    CLASS_ALIASES,
    ENUM_FIELD_IMPORTS,
    ENUM_NAME_OVERRIDES,
    EXCLUDED_PARAM_NAMES,
    EXTRA_FIELDS,
    FIELD_RENAMES,
    REQUEST_CLASS_NAME_OVERRIDES,
    SCHEMA_CLASS_OVERRIDES,
)

ROOT = Path(__file__).resolve().parents[1]
AUGMENTED_SPEC_PATH = Path(__file__).parent / ".prime-public-api-spec.augmented.yaml"
OUTPUT_PATH = ROOT / "prime_sdk" / "generated" / "models.py"
SURFACE_PATH = ROOT / "tests" / "fixtures" / "model_surface.json"
TYPES_PATH = ROOT / "tests" / "fixtures" / "model_types.json"

FILE_HEADER = """\
# Copyright 2026-present Coinbase Global, Inc.
#
# This file is generated by apiSpec/generate_models.py
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Do not edit this file manually.

from __future__ import annotations

from dataclasses import dataclass

"""

REF_PATTERN = re.compile(r"^#/components/schemas/(.+)$")

PINNED_TYPE_REMAP = {
    "CrossMarginSummary": "XMSummary",
}

SCHEMA_REF_TYPE_OVERRIDES = {
    "google.type.Date": "str",
}

DOCSTRING_WRAP_WIDTH = 88


CLASS_NAME_PREFIXES = (
    "coinbase_brokerage_proxy_events_materialized_api_",
    "coinbase_public_rest_api_",
    "coinbase_custody_api_",
    "CoinbaseBrokerageProxyEventsMaterializedApi",
    "coinbaseBrokerageProxyEventsMaterializedApi",
    "CoinbasePublicRestApi",
    "coinbasePublicRestApi",
    "CoinbaseCustodyApi",
    "coinbaseCustodyApi",
    "PrimeRESTAPI",
    "primeRESTAPI",
    "PrimeBeta",
    "primeBeta",
    "public_rest_api",
)


def short_name(schema_key: str) -> str:
    name = schema_key.split(".")[-1]
    for prefix in CLASS_NAME_PREFIXES:
        if name.startswith(prefix):
            return name[len(prefix) :]
    return name


def class_name_for_schema(schema_key: str) -> str:
    if schema_key in ENUM_NAME_OVERRIDES:
        return ENUM_NAME_OVERRIDES[schema_key]
    if schema_key in SCHEMA_CLASS_OVERRIDES:
        return SCHEMA_CLASS_OVERRIDES[schema_key]
    return short_name(schema_key)


def load_compat() -> tuple[dict[str, list[str]], dict[str, dict[str, str]]]:
    surface = json.loads(SURFACE_PATH.read_text(encoding="utf-8"))
    types = json.loads(TYPES_PATH.read_text(encoding="utf-8"))
    return surface, types


def resolve_ref(ref: str, schemas: dict[str, Any]) -> str | None:
    match = REF_PATTERN.match(ref)
    if not match:
        return None
    schema_key = match.group(1)
    if schema_key in SCHEMA_REF_TYPE_OVERRIDES:
        return SCHEMA_REF_TYPE_OVERRIDES[schema_key]
    if schema_key not in schemas:
        return None
    schema = schemas[schema_key]
    if "enum" in schema:
        return "str"
    return class_name_for_schema(schema_key)


def schema_property_type(
    prop: dict[str, Any],
    schemas: dict[str, Any],
    class_short_name: str,
    field_name: str,
    compat_types: dict[str, dict[str, str]],
) -> str:
    alias_targets = {v: k for k, v in CLASS_ALIASES.items()}
    public_class = alias_targets.get(class_short_name, class_short_name)
    pinned = compat_types.get(public_class, {}).get(field_name)
    if pinned:
        pinned = PINNED_TYPE_REMAP.get(pinned, pinned)
        if pinned != "list" and not pinned.startswith("list["):
            return pinned

    enum_import = ENUM_FIELD_IMPORTS.get(class_short_name, {}).get(field_name)
    if enum_import:
        return enum_import

    if "$ref" in prop:
        resolved = resolve_ref(prop["$ref"], schemas)
        return resolved or "str"

    prop_type = prop.get("type")
    if prop_type == "string":
        return "str"
    if prop_type == "integer":
        return "str"
    if prop_type == "number":
        return "str"
    if prop_type == "boolean":
        return "bool"
    if prop_type == "array":
        items = prop.get("items", {})
        if "$ref" in items:
            inner = resolve_ref(items["$ref"], schemas) or "str"
            return f"list[{inner}]"
        inner_type = schema_property_type(
            items, schemas, class_short_name, field_name, compat_types
        )
        return f"list[{inner_type}]"
    if prop_type == "object":
        return "dict[str, Any]"

    for combinator in ("allOf", "anyOf", "oneOf"):
        options = prop.get(combinator)
        if isinstance(options, list) and options:
            return schema_property_type(
                options[0], schemas, class_short_name, field_name, compat_types
            )

    return "str"


def operation_id_to_class_name(operation_id: str) -> str:
    if operation_id in REQUEST_CLASS_NAME_OVERRIDES:
        return REQUEST_CLASS_NAME_OVERRIDES[operation_id]
    name = operation_id
    for prefix in ("PrimeRESTAPI_", "primeRESTAPI_"):
        name = name.removeprefix(prefix)
    if not name.endswith("Request"):
        name = f"{name}Request"
    return name


def is_valid_param_field_name(name: str) -> bool:
    return name.isidentifier() and name not in EXCLUDED_PARAM_NAMES


def collect_operation_parameter_names(operation: dict[str, Any]) -> list[str]:
    names: list[str] = []
    for param in operation.get("parameters") or []:
        if not isinstance(param, dict):
            continue
        if param.get("in") not in ("path", "query"):
            continue
        name = param.get("name")
        if isinstance(name, str) and is_valid_param_field_name(name):
            names.append(name)
    return names


def collect_operation_parameter_locations(
    operation: dict[str, Any],
    class_short: str,
) -> dict[str, str]:
    renames = FIELD_RENAMES.get(class_short, {})
    locations: dict[str, str] = {}
    seen: set[str] = set()

    for param in operation.get("parameters") or []:
        if not isinstance(param, dict):
            continue
        param_in = param.get("in")
        if param_in not in ("path", "query"):
            continue
        spec_name = param.get("name")
        if not isinstance(spec_name, str) or not is_valid_param_field_name(spec_name):
            continue
        public_name = renames.get(spec_name, spec_name)
        if public_name in seen:
            continue
        seen.add(public_name)
        locations[public_name] = param_in

    return locations


def collect_operation_parameter_fields(
    operation: dict[str, Any],
    schemas: dict[str, Any],
    compat_types: dict[str, dict[str, str]],
    class_short: str,
) -> list[tuple[str, str]]:
    renames = FIELD_RENAMES.get(class_short, {})
    fields: list[tuple[str, str]] = []
    seen: set[str] = set()

    for param in operation.get("parameters") or []:
        if not isinstance(param, dict):
            continue
        if param.get("in") not in ("path", "query"):
            continue
        spec_name = param.get("name")
        if not isinstance(spec_name, str) or not is_valid_param_field_name(spec_name):
            continue
        public_name = renames.get(spec_name, spec_name)
        if public_name in seen:
            continue
        seen.add(public_name)
        schema = param.get("schema")
        if not isinstance(schema, dict):
            schema = {}
        field_type = schema_property_type(
            schema, schemas, class_short, public_name, compat_types
        )
        fields.append((public_name, field_type))

    return fields


def collect_operation_docs(
    operation: dict[str, Any],
    body_schema: dict[str, Any] | None,
) -> tuple[str | None, dict[str, str], list[str]]:
    summary = operation.get("summary") or operation.get("description")
    class_summary = normalize_description(str(summary)) if summary else None

    descriptions: dict[str, str] = {}
    field_order: list[str] = []

    for param in operation.get("parameters") or []:
        if not isinstance(param, dict):
            continue
        if param.get("in") not in ("path", "query"):
            continue
        name = param.get("name")
        description = param.get("description")
        if not isinstance(name, str) or not is_valid_param_field_name(name):
            continue
        field_order.append(name)
        if description:
            descriptions[name] = normalize_description(str(description))

    if body_schema:
        body_descriptions = collect_field_descriptions(body_schema, {})
        for name, description in body_descriptions.items():
            if name not in descriptions:
                field_order.append(name)
            descriptions[name] = description

    return class_summary, descriptions, field_order


def collect_all_operations(
    spec: dict[str, Any],
) -> dict[str, tuple[str, dict[str, Any], dict[str, Any] | None]]:
    operations: dict[str, tuple[str, dict[str, Any], dict[str, Any] | None]] = {}
    for methods in (spec.get("paths") or {}).values():
        for method, operation in methods.items():
            if method.lower() not in {
                "get",
                "post",
                "put",
                "patch",
                "delete",
            } or not isinstance(operation, dict):
                continue
            operation_id = operation.get("operationId")
            if not operation_id:
                continue
            class_name = operation_id_to_class_name(operation_id)
            body_schema = (
                operation.get("requestBody", {})
                .get("content", {})
                .get("application/json", {})
                .get("schema")
            )
            if not isinstance(body_schema, dict):
                body_schema = None
            operations[class_name] = (operation_id, operation, body_schema)
    return operations


def collect_inline_fields(
    class_short: str,
    schema: dict[str, Any],
    schemas: dict[str, Any],
    compat_types: dict[str, dict[str, str]],
) -> list[tuple[str, str]]:
    renames = FIELD_RENAMES.get(class_short, {})
    fields: list[tuple[str, str]] = []
    for spec_name, prop in (schema.get("properties") or {}).items():
        if not isinstance(prop, dict):
            continue
        public_name = renames.get(spec_name, spec_name)
        field_type = schema_property_type(
            prop, schemas, class_short, public_name, compat_types
        )
        fields.append((public_name, field_type))
    return fields


def append_extra_operation_fields(
    class_short: str,
    fields: list[tuple[str, str]],
    compat_types: dict[str, dict[str, str]],
) -> list[tuple[str, str]]:
    extra_fields = EXTRA_FIELDS.get(class_short)
    if not extra_fields:
        return fields
    alias_targets = {v: k for k, v in CLASS_ALIASES.items()}
    public_class = alias_targets.get(class_short, class_short)
    existing = {name for name, _ in fields}
    result = list(fields)
    for extra_name, extra_type in extra_fields.items():
        if extra_name in existing:
            continue
        pinned = compat_types.get(public_class, {}).get(extra_name, extra_type)
        result.append((extra_name, pinned))
    return result


def collect_fields(
    schema_key: str,
    schema: dict[str, Any],
    schemas: dict[str, Any],
    compat_surface: dict[str, list[str]],
    compat_types: dict[str, dict[str, str]],
) -> list[tuple[str, str]]:
    class_short = class_name_for_schema(schema_key)
    renames = FIELD_RENAMES.get(class_short, {})
    properties = dict(schema.get("properties") or {})

    alias_targets = {v: k for k, v in CLASS_ALIASES.items()}
    public_class = alias_targets.get(class_short, class_short)

    fields: list[tuple[str, str]] = []
    seen: set[str] = set()

    def add_field(field_name: str, field_type: str) -> None:
        if field_name in seen:
            return
        seen.add(field_name)
        fields.append((field_name, field_type))

    for spec_name, prop in properties.items():
        public_name = renames.get(spec_name, spec_name)
        field_type = schema_property_type(
            prop, schemas, class_short, public_name, compat_types
        )
        add_field(public_name, field_type)

    for extra_name, extra_type in EXTRA_FIELDS.get(class_short, {}).items():
        pinned = compat_types.get(public_class, {}).get(extra_name, extra_type)
        add_field(extra_name, pinned)

    desired_order = compat_surface.get(public_class)
    if desired_order:
        ordered: list[tuple[str, str]] = []
        field_map = dict(fields)
        for name in desired_order:
            if name in field_map:
                ordered.append((name, field_map[name]))
        for name, field_type in fields:
            if name not in desired_order:
                ordered.append((name, field_type))
        return ordered

    return fields


def normalize_description(text: str) -> str:
    return " ".join(str(text).split())


def escape_docstring(text: str) -> str:
    return text.replace("\\", "\\\\").replace('"""', '\\"\\"\\"')


def collect_class_docstring(schema: dict[str, Any]) -> str | None:
    summary = schema.get("description") or schema.get("title")
    if not summary:
        return None
    return normalize_description(str(summary))


def collect_field_descriptions(
    schema: dict[str, Any], renames: dict[str, str]
) -> dict[str, str]:
    descriptions: dict[str, str] = {}
    for spec_name, prop in (schema.get("properties") or {}).items():
        if not isinstance(prop, dict):
            continue
        description = prop.get("description")
        if not description:
            continue
        public_name = renames.get(spec_name, spec_name)
        descriptions[public_name] = normalize_description(str(description))
    return descriptions


def render_docstring_lines(
    class_summary: str | None,
    field_descriptions: dict[str, str],
    field_order: list[str],
) -> list[str]:
    attribute_entries: list[str] = []
    for field_name in field_order:
        if field_name in field_descriptions:
            attribute_entries.append(
                f"{field_name}: {escape_docstring(field_descriptions[field_name])}"
            )

    if not class_summary and not attribute_entries:
        return []

    lines: list[str] = []
    if class_summary:
        lines.append(escape_docstring(class_summary))
    if attribute_entries:
        if lines:
            lines.append("")
        lines.append("Attributes:")
        for entry in attribute_entries:
            wrapped = textwrap.fill(
                entry,
                width=DOCSTRING_WRAP_WIDTH,
                initial_indent="    ",
                subsequent_indent="        ",
            )
            lines.extend(wrapped.splitlines())

    return lines


def topological_sort(
    object_schemas: dict[str, dict[str, Any]], schemas: dict[str, Any]
) -> list[str]:
    dependencies: dict[str, set[str]] = defaultdict(set)
    ordered: list[str] = []

    def add_deps(prop: dict[str, Any], class_short: str) -> None:
        if "$ref" in prop:
            resolved = resolve_ref(prop["$ref"], schemas)
            if resolved and resolved != class_short:
                dependencies[class_short].add(resolved)
        if prop.get("type") == "array":
            items = prop.get("items", {})
            if "$ref" in items:
                resolved = resolve_ref(items["$ref"], schemas)
                if resolved and resolved != class_short:
                    dependencies[class_short].add(resolved)

    for schema_key, schema in object_schemas.items():
        class_short = class_name_for_schema(schema_key)
        for prop in (schema.get("properties") or {}).values():
            add_deps(prop, class_short)

    remaining = dict(object_schemas)

    while remaining:
        progressed = False
        for schema_key in list(remaining):
            class_short = class_name_for_schema(schema_key)
            if dependencies[class_short].issubset(set(ordered) | {class_short}):
                ordered.append(class_short)
                del remaining[schema_key]
                progressed = True
        if not progressed:
            ordered.extend(class_name_for_schema(key) for key in remaining)
            break

    seen: set[str] = set()
    deduped: list[str] = []
    for name in ordered:
        if name not in seen:
            seen.add(name)
            deduped.append(name)
    return deduped


def render_class(
    class_short: str,
    fields: list[tuple[str, str]],
    schema: dict[str, Any],
    *,
    kw_only: bool = False,
    class_summary: str | None = None,
    field_descriptions: dict[str, str] | None = None,
    field_order: list[str] | None = None,
    field_locations: dict[str, str] | None = None,
) -> str:
    renames = FIELD_RENAMES.get(class_short, {})
    if class_summary is None:
        class_summary = collect_class_docstring(schema)
    if field_descriptions is None:
        field_descriptions = collect_field_descriptions(schema, renames)
    if field_order is None:
        field_order = [name for name, _ in fields]
    docstring_lines = render_docstring_lines(
        class_summary, field_descriptions, field_order
    )

    decorator = "@dataclass(kw_only=True)" if kw_only else "@dataclass"
    lines = [decorator, f"class {class_short}:"]
    if docstring_lines:
        lines.append('    """')
        for line in docstring_lines:
            lines.append(f"    {line}" if line else "")
        lines.append('    """')

    if not fields:
        if not docstring_lines:
            lines.append("    pass")
        return "\n".join(lines)

    for field_name, field_type in fields:
        location = (field_locations or {}).get(field_name)
        if location in ("path", "query"):
            lines.append(
                f'    {field_name}: {field_type} = field(default=None, metadata={{"location": "{location}"}})'
            )
        else:
            lines.append(f"    {field_name}: {field_type} = None")

    return "\n".join(lines)


def generate_models() -> str:
    with AUGMENTED_SPEC_PATH.open(encoding="utf-8") as handle:
        spec = yaml.safe_load(handle)

    schemas: dict[str, Any] = spec["components"]["schemas"]
    object_schemas = {
        key: value
        for key, value in schemas.items()
        if isinstance(value, dict)
        and "enum" not in value
        and not key.startswith("google.")
    }

    compat_surface, compat_types = load_compat()
    order = topological_sort(object_schemas, schemas)

    schema_by_short: dict[str, tuple[str, dict[str, Any]]] = {}
    for schema_key, schema in object_schemas.items():
        schema_by_short[class_name_for_schema(schema_key)] = (schema_key, schema)

    enum_imports = {
        import_name
        for field_map in ENUM_FIELD_IMPORTS.values()
        for import_name in field_map.values()
    }
    imports: list[str] = []
    if enum_imports:
        imports.append("from typing import Any\n")
        imports.append("from prime_sdk.enums import " + ", ".join(sorted(enum_imports)))
        imports.append("")

    body_parts: list[str] = []
    emitted: set[str] = set()

    for class_short in order:
        if class_short in emitted or class_short not in schema_by_short:
            continue
        schema_key, schema = schema_by_short[class_short]
        fields = collect_fields(
            schema_key, schema, schemas, compat_surface, compat_types
        )
        body_parts.append(render_class(class_short, fields, schema))
        body_parts.append("")
        emitted.add(class_short)

    operations = collect_all_operations(spec)
    if operations:
        body_parts.append("# Inline request models from OpenAPI paths")
        body_parts.append("")
    for class_short in sorted(operations):
        if class_short in emitted:
            continue
        _operation_id, operation, body_schema = operations[class_short]
        class_summary, field_descriptions, field_order = collect_operation_docs(
            operation, body_schema
        )
        if body_schema:
            param_fields = collect_operation_parameter_fields(
                operation, schemas, compat_types, class_short
            )
            body_fields = collect_inline_fields(
                class_short, body_schema, schemas, compat_types
            )
            param_names = {name for name, _ in param_fields}
            fields = param_fields + [
                (name, field_type)
                for name, field_type in body_fields
                if name not in param_names
            ]
            field_locations = collect_operation_parameter_locations(
                operation, class_short
            )
        else:
            fields = collect_operation_parameter_fields(
                operation, schemas, compat_types, class_short
            )
            field_locations = None
        fields = append_extra_operation_fields(class_short, fields, compat_types)
        body_parts.append(
            render_class(
                class_short,
                fields,
                body_schema or {},
                kw_only=True,
                class_summary=class_summary,
                field_descriptions=field_descriptions,
                field_order=field_order,
                field_locations=field_locations,
            )
        )
        body_parts.append("")
        emitted.add(class_short)

    alias_lines = ["", "# Backward-compatible public aliases"]
    for public_name, generated_name in sorted(CLASS_ALIASES.items()):
        alias_lines.append(f"{public_name} = {generated_name}")

    body_text = "\n".join(body_parts)
    if ": datetime" in body_text:
        imports.insert(0, "from datetime import datetime\n")

    header = FILE_HEADER
    if "= field(default=None" in body_text:
        header = header.replace(
            "from dataclasses import dataclass",
            "from dataclasses import dataclass, field",
        )

    return header + "\n".join(imports) + body_text + "\n".join(alias_lines) + "\n"


def main() -> None:
    if not AUGMENTED_SPEC_PATH.exists():
        raise SystemExit(
            f"Augmented spec not found at {AUGMENTED_SPEC_PATH}. Run `make promote-titles` first."
        )

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    content = generate_models()
    OUTPUT_PATH.write_text(content, encoding="utf-8")
    print(f"Generated {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
