# Copyright 2026-present Coinbase Global, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Generate dataclass models from the Prime OpenAPI specification."""

from __future__ import annotations

import json
import re
from collections import defaultdict
from pathlib import Path
from typing import Any

import yaml
from model_config import (
    CLASS_ALIASES,
    ENUM_FIELD_IMPORTS,
    ENUM_NAME_OVERRIDES,
    EXTRA_FIELDS,
    FIELD_RENAMES,
    LOCATE_REQUEST_CLASS,
)

ROOT = Path(__file__).resolve().parents[1]
AUGMENTED_SPEC_PATH = Path(__file__).parent / ".prime-public-api-spec.augmented.yaml"
OUTPUT_PATH = ROOT / "prime_sdk" / "generated" / "models.py"
SURFACE_PATH = ROOT / "tests" / "fixtures" / "model_surface.json"
TYPES_PATH = ROOT / "tests" / "fixtures" / "model_types.json"

FILE_HEADER = '''\
# Copyright 2026-present Coinbase Global, Inc.
#
# This file is generated by apiSpec/generate_models.py
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Do not edit this file manually.

from __future__ import annotations

from dataclasses import dataclass

'''

REF_PATTERN = re.compile(r"^#/components/schemas/(.+)$")

PINNED_TYPE_REMAP = {
    "CrossMarginSummary": "XMSummary",
}

SCHEMA_REF_TYPE_OVERRIDES = {
    "google.type.Date": "str",
}


CLASS_NAME_PREFIXES = (
    "coinbase_brokerage_proxy_events_materialized_api_",
    "coinbase_public_rest_api_",
    "coinbase_custody_api_",
    "CoinbaseBrokerageProxyEventsMaterializedApi",
    "coinbaseBrokerageProxyEventsMaterializedApi",
    "CoinbasePublicRestApi",
    "coinbasePublicRestApi",
    "CoinbaseCustodyApi",
    "coinbaseCustodyApi",
    "PrimeRESTAPI",
    "primeRESTAPI",
    "PrimeBeta",
    "primeBeta",
    "public_rest_api",
)


def short_name(schema_key: str) -> str:
    name = schema_key.split(".")[-1]
    for prefix in CLASS_NAME_PREFIXES:
        if name.startswith(prefix):
            return name[len(prefix) :]
    return name


def class_name_for_schema(schema_key: str) -> str:
    if schema_key in ENUM_NAME_OVERRIDES:
        return ENUM_NAME_OVERRIDES[schema_key]
    name = short_name(schema_key)
    if name == "Locate" and schema_key.endswith(".Locate"):
        return LOCATE_REQUEST_CLASS
    return name


def load_compat() -> tuple[dict[str, list[str]], dict[str, dict[str, str]]]:
    surface = json.loads(SURFACE_PATH.read_text(encoding="utf-8"))
    types = json.loads(TYPES_PATH.read_text(encoding="utf-8"))
    return surface, types


def resolve_ref(ref: str, schemas: dict[str, Any]) -> str | None:
    match = REF_PATTERN.match(ref)
    if not match:
        return None
    schema_key = match.group(1)
    if schema_key in SCHEMA_REF_TYPE_OVERRIDES:
        return SCHEMA_REF_TYPE_OVERRIDES[schema_key]
    if schema_key not in schemas:
        return None
    schema = schemas[schema_key]
    if "enum" in schema:
        return "str"
    return class_name_for_schema(schema_key)


def schema_property_type(
    prop: dict[str, Any],
    schemas: dict[str, Any],
    class_short_name: str,
    field_name: str,
    compat_types: dict[str, dict[str, str]],
) -> str:
    alias_targets = {v: k for k, v in CLASS_ALIASES.items()}
    public_class = alias_targets.get(class_short_name, class_short_name)
    pinned = compat_types.get(public_class, {}).get(field_name)
    if pinned:
        pinned = PINNED_TYPE_REMAP.get(pinned, pinned)
        if pinned != "list" and not pinned.startswith("list["):
            return pinned

    enum_import = ENUM_FIELD_IMPORTS.get(class_short_name, {}).get(field_name)
    if enum_import:
        return enum_import

    if "$ref" in prop:
        resolved = resolve_ref(prop["$ref"], schemas)
        return resolved or "str"

    prop_type = prop.get("type")
    if prop_type == "string":
        return "str"
    if prop_type == "integer":
        return "str"
    if prop_type == "number":
        return "str"
    if prop_type == "boolean":
        return "bool"
    if prop_type == "array":
        items = prop.get("items", {})
        if "$ref" in items:
            inner = resolve_ref(items["$ref"], schemas) or "str"
            return f"list[{inner}]"
        inner_type = schema_property_type(
            items, schemas, class_short_name, field_name, compat_types
        )
        return f"list[{inner_type}]"
    if prop_type == "object":
        return "dict[str, Any]"

    for combinator in ("allOf", "anyOf", "oneOf"):
        options = prop.get(combinator)
        if isinstance(options, list) and options:
            return schema_property_type(
                options[0], schemas, class_short_name, field_name, compat_types
            )

    return "str"


def collect_fields(
    schema_key: str,
    schema: dict[str, Any],
    schemas: dict[str, Any],
    compat_surface: dict[str, list[str]],
    compat_types: dict[str, dict[str, str]],
) -> list[tuple[str, str]]:
    class_short = class_name_for_schema(schema_key)
    renames = FIELD_RENAMES.get(class_short, {})
    properties = dict(schema.get("properties") or {})

    alias_targets = {v: k for k, v in CLASS_ALIASES.items()}
    public_class = alias_targets.get(class_short, class_short)

    fields: list[tuple[str, str]] = []
    seen: set[str] = set()

    def add_field(field_name: str, field_type: str) -> None:
        if field_name in seen:
            return
        seen.add(field_name)
        fields.append((field_name, field_type))

    for spec_name, prop in properties.items():
        public_name = renames.get(spec_name, spec_name)
        field_type = schema_property_type(
            prop, schemas, class_short, public_name, compat_types
        )
        add_field(public_name, field_type)

    for extra_name, extra_type in EXTRA_FIELDS.get(class_short, {}).items():
        pinned = compat_types.get(public_class, {}).get(extra_name, extra_type)
        add_field(extra_name, pinned)

    desired_order = compat_surface.get(public_class)
    if desired_order:
        ordered: list[tuple[str, str]] = []
        field_map = dict(fields)
        for name in desired_order:
            if name in field_map:
                ordered.append((name, field_map[name]))
        for name, field_type in fields:
            if name not in desired_order:
                ordered.append((name, field_type))
        return ordered

    return fields


def topological_sort(
    object_schemas: dict[str, dict[str, Any]], schemas: dict[str, Any]
) -> list[str]:
    dependencies: dict[str, set[str]] = defaultdict(set)
    ordered: list[str] = []

    def add_deps(prop: dict[str, Any], class_short: str) -> None:
        if "$ref" in prop:
            resolved = resolve_ref(prop["$ref"], schemas)
            if resolved and resolved != class_short:
                dependencies[class_short].add(resolved)
        if prop.get("type") == "array":
            items = prop.get("items", {})
            if "$ref" in items:
                resolved = resolve_ref(items["$ref"], schemas)
                if resolved and resolved != class_short:
                    dependencies[class_short].add(resolved)

    for schema_key, schema in object_schemas.items():
        class_short = class_name_for_schema(schema_key)
        for prop in (schema.get("properties") or {}).values():
            add_deps(prop, class_short)

    remaining = dict(object_schemas)

    while remaining:
        progressed = False
        for schema_key in list(remaining):
            class_short = class_name_for_schema(schema_key)
            if dependencies[class_short].issubset(set(ordered) | {class_short}):
                ordered.append(class_short)
                del remaining[schema_key]
                progressed = True
        if not progressed:
            ordered.extend(class_name_for_schema(key) for key in remaining)
            break

    seen: set[str] = set()
    deduped: list[str] = []
    for name in ordered:
        if name not in seen:
            seen.add(name)
            deduped.append(name)
    return deduped


def render_class(
    class_short: str,
    fields: list[tuple[str, str]],
) -> str:
    lines = ["@dataclass", f"class {class_short}:"]
    if not fields:
        lines.append("    pass")
        return "\n".join(lines)

    for field_name, field_type in fields:
        lines.append(f"    {field_name}: {field_type} = None")

    return "\n".join(lines)


def generate_models() -> str:
    with AUGMENTED_SPEC_PATH.open(encoding="utf-8") as handle:
        spec = yaml.safe_load(handle)

    schemas: dict[str, Any] = spec["components"]["schemas"]
    object_schemas = {
        key: value
        for key, value in schemas.items()
        if isinstance(value, dict)
        and "enum" not in value
        and not key.startswith("google.")
    }

    compat_surface, compat_types = load_compat()
    order = topological_sort(object_schemas, schemas)

    schema_by_short: dict[str, tuple[str, dict[str, Any]]] = {}
    for schema_key, schema in object_schemas.items():
        schema_by_short[class_name_for_schema(schema_key)] = (schema_key, schema)

    enum_imports = {
        import_name
        for field_map in ENUM_FIELD_IMPORTS.values()
        for import_name in field_map.values()
    }
    imports = ["from typing import Any\n"] if enum_imports else []
    if enum_imports:
        imports.append("from prime_sdk.enums import " + ", ".join(sorted(enum_imports)))
        imports.append("")

    body_parts: list[str] = []
    emitted: set[str] = set()

    for class_short in order:
        if class_short in emitted or class_short not in schema_by_short:
            continue
        schema_key, schema = schema_by_short[class_short]
        fields = collect_fields(
            schema_key, schema, schemas, compat_surface, compat_types
        )
        body_parts.append(render_class(class_short, fields))
        body_parts.append("")
        emitted.add(class_short)

    alias_lines = ["", "# Backward-compatible public aliases"]
    for public_name, generated_name in sorted(CLASS_ALIASES.items()):
        alias_lines.append(f"{public_name} = {generated_name}")

    return FILE_HEADER + "\n".join(imports) + "\n".join(body_parts) + "\n".join(
        alias_lines
    ) + "\n"


def main() -> None:
    if not AUGMENTED_SPEC_PATH.exists():
        raise SystemExit(
            f"Augmented spec not found at {AUGMENTED_SPEC_PATH}. Run `make promote-titles` first."
        )

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    content = generate_models()
    OUTPUT_PATH.write_text(content, encoding="utf-8")
    print(f"Generated {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
