# Copyright 2024-present Coinbase Global, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from dataclasses import dataclass

from ...base_request import BaseRequest
from ...base_response import BaseResponse
from ...model import CreateOrderRequest as _CreateOrderRequest
from ...model import CreateOrderResponse as _CreateOrderResponse


@dataclass(kw_only=True)
class CreateOrderRequest(BaseRequest, _CreateOrderRequest):
    """
    Create Order

    Attributes:
        portfolio_id: The ID of the portfolio that owns the order
        product_id: The ID of the product being traded for the order (e.g. `BTC-USD`)
        client_order_id: A client-generated order ID used for reference purposes
        base_quantity: Order size in base asset units (either `base_quantity` or
            `quote_value` is required)
        quote_value: Order size in quote asset units, i.e. the amount the user wants to
            spend (when buying) or receive (when selling); the quantity in base units will
            be determined based on the market liquidity and indicated `quote_value` (either
            `base_quantity` or `quote_value` is required)
        limit_price: The limit price (required for TWAP, VWAP, LIMIT, and STOP_LIMIT orders)
        start_time: The start time of the order in UTC (TWAP only)
        expiry_time: The expiry time of the order in UTC (TWAP, VWAP, LIMIT, and STOP_LIMIT
            GTD only)
        stp_id: An optional self trade prevention id (in the form of a UUID). The value is
            only honored for certain clients who are permitted to specify a custom self
            trade prevention id
        display_quote_size: Optionally specify a display size. This is the maximum order
            size that will show up on venue order books. Specifying a value here effectively
            makes a LIMIT order into an "iceberg" style order. This property only applies to
            LIMIT orders and will be ignored for other order types.
        historical_pov: Historical percentage of volume
        stop_price: Specifies the stop price at which the order activates. The order is
            activated if the last trade price on Coinbase Exchange crosses the stop price
            specified on the order
        settl_currency: The currency in which the settlement will be made
        post_only: Post-only flag - when true, the order will only be posted to the order
            book and not immediately matched. Only applicable to LIMIT orders with GTC or
            GTD time in force.
        offset: Offset value for PEG orders. 0 means peg to BBO. Only non-negative values
            are allowed (PEG orders only)
        wig_level: WIG (Would if Good) level - the best price a pegged order would be placed
            on venues, opposite to limit_price (PEG orders only)
        is_buy_exact: Buy Exact order flag. When true, fees for a BUY order sized in
            quote_value are charged on top of the requested quote_value instead of being
            carved out of it. Only valid for BUY orders sized in quote_value on SPOT
            products.
    """


@dataclass
class CreateOrderResponse(BaseResponse, _CreateOrderResponse):
    """
    Attributes:
        order_id: The order ID generated by Coinbase
    """
