# Copyright 2025-present Coinbase Global, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from dataclasses import dataclass

from ...base_request import BaseRequest
from ...base_response import BaseResponse
from ...model import GetOrderRequest as _GetOrderRequest
from ...model import GetOrderResponse as _GetOrderResponse


@dataclass(kw_only=True)
class GetOrderRequest(BaseRequest, _GetOrderRequest):
    """
    Get Order by Order ID

    Attributes:
        portfolio_id: Portfolio ID
        order_id: Order ID
    """


@dataclass
class GetOrderResponse(BaseResponse, _GetOrderResponse):
    """
    Attributes:
        order.id: The unique order ID generated by Coinbase
        order.user_id: The ID of the user that created the order
        order.portfolio_id: The ID of the portfolio that owns the order
        order.product_id: The ID of the product being traded by the order
        order.client_order_id: A client-generated order ID used for reference purposes
            (note: order will be rejected if this ID is not unique among all currently
            active orders)
        order.base_quantity: Order size in base asset units (either `base_quantity` or
            `quote_value` is required)
        order.quote_value: Order size in quote asset units, i.e. the amount the user wants
            to spend (when buying) or receive (when selling); the quantity in base units
            will be determined based on the market liquidity and indicated `quote_value`.
            Either `base_quantity` or `quote_value` is required
        order.limit_price: The limit price (required for TWAP, VWAP, LIMIT and STOP_LIMIT
            orders)
        order.start_time: The start time of the order in UTC (only applies to TWAP, VWAP
            orders.)
        order.expiry_time: The expiry time of the order in UTC (applies to TWAP, VWAP,
            LIMIT, and STOP_LIMIT orders with `time_in_force` set to `GTD`)
        order.created_at: The order creation time as a UTC timestamp
        order.filled_quantity: Size filled (in base asset units)
        order.filled_value: Market value filled (in quote asset units)
        order.average_filled_price: Indicates the average `filled_price`
        order.commission: Total commission paid on this order (in quote asset units) -- only
            applicable for partially- or fully-filled orders
        order.exchange_fee: Fee charged by the exchange for Cost Plus commission
            configurations. Exchange fee will be 0 for All In commission configurations.
        order.historical_pov: historical pov for the order
        order.stop_price: Specifies the stop price at which the order activates. The order
            is activated if the last trade price on Coinbase Exchange crosses the stop price
            specified on the order
        order.net_average_filled_price: Indicates the average `filled_price` net of
            commissions and fees
        order.user_context: Indicates a user friendly message for regarding various aspects
            of the order such as cancellation or rejection reasons
        order.client_product_id: The client product ID of the fill indictating the settlment
            currency
        order.post_only: Post-only flag - indicates whether the order was placed as post-
            only
        order.order_edit_history: The history of order edits (deprecated: use edit_history
            instead)
        order.is_raise_exact: Indicates if this was a raise exact order (size inclusive of
            fees for sell orders in quote)
        order.display_size: Display size for the order
        order.edit_history: The history of order edits
        order.display_quote_size: The maximum order size that will show up on venue order
            books (in quote currency).
        order.display_base_size: The maximum order size that will show up on venue order
            books (in base currency).
        order.peg_offset_type: The peg offset type for PEG orders (PRICE, BASIS_POINTS, or
            CUMULATIVE_DEPTH_IN_BASE_UNITS)
        order.offset: The offset value for PEG orders
        order.wig_level: The wig (would if good) level for PEG orders - best price opposite
            to limit_price
        order.is_buy_exact: Indicates if this was a buy exact order (fees charged on top of
            quote size for BUY orders sized in quote)
    """
