# Copyright 2025-present Coinbase Global, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from enum import Enum


class WalletType(Enum):
    VAULT = "VAULT"
    TRADING = "TRADING"
    ONCHAIN = "ONCHAIN"
    OTHER = "WALLET_TYPE_OTHER"
    QC = "QC"


class WalletDepositType(Enum):
    WIRE = "WIRE"
    SWIFT = "SWIFT"
    CRYPTO = "CRYPTO"
    SEPA = "SEPA"


class BalanceType(Enum):
    TRADING = "TRADING_BALANCES"
    VAULT = "VAULT_BALANCES"
    TOTAL = "TOTAL_BALANCES"
    UNKNOWN_BALANCE_TYPE = "UNKNOWN_BALANCE_TYPE"
    PRIME_CUSTODY_BALANCES = "PRIME_CUSTODY_BALANCES"


class NetworkType(Enum):
    NETWORK_TYPE_UNSPECIFIED = "NETWORK_TYPE_UNSPECIFIED"
    NETWORK_TYPE_EVM = "NETWORK_TYPE_EVM"
    NETWORK_TYPE_SOLANA = "NETWORK_TYPE_SOLANA"


class OrderSide(Enum):
    BUY = "BUY"
    SELL = "SELL"


class OrderType(Enum):
    MARKET = "MARKET"
    LIMIT = "LIMIT"
    TWAP = "TWAP"
    BLOCK = "BLOCK"
    VWAP = "VWAP"
    STOP_LIMIT = "STOP_LIMIT"
    RFQ = "RFQ"


class TimeInForce(Enum):
    GOOD_UNTIL_DATE_TIME = "GOOD_UNTIL_DATE_TIME"
    GOOD_UNTIL_CANCELLED = "GOOD_UNTIL_CANCELLED"
    IMMEDIATE_OR_CANCEL = "IMMEDIATE_OR_CANCEL"
    FILL_OR_KILL = "FILL_OR_KILL"
    UNKNOWN_TIME_IN_FORCE = "UNKNOWN_TIME_IN_FORCE"


class SizeType(Enum):
    ALLOCATION_SIZE_TYPE_UNKNOWN = "ALLOCATION_SIZE_TYPE_UNKNOWN"
    BASE = "BASE"
    QUOTE = "QUOTE"
    PERCENT = "PERCENT"


class ActivityLevel(Enum):
    ACTIVITY_LEVEL_ALL = "ACTIVITY_LEVEL_ALL"
    ACTIVITY_LEVEL_ENTITY = "ACTIVITY_LEVEL_ENTITY"
    ACTIVITY_LEVEL_PORTFOLIO = "ACTIVITY_LEVEL_PORTFOLIO"


class AggregationType(Enum):
    UNKNOWN_BALANCE_TYPE = "UNKNOWN_BALANCE_TYPE"
    TRADING_BALANCES = "TRADING_BALANCES"
    VAULT_BALANCES = "VAULT_BALANCES"
    TOTAL_BALANCES = "TOTAL_BALANCES"
    PRIME_CUSTODY_BALANCES = "PRIME_CUSTODY_BALANCES"
    UNIFIED_TOTAL_BALANCES = "UNIFIED_TOTAL_BALANCES"


class UnstakeEstimateType(Enum):
    UNSPECIFIED = "UNSPECIFIED"
    LIVE = "LIVE"
    INTERIM = "INTERIM"


class UnstakeType(Enum):
    UNSTAKE_TYPE_UNSPECIFIED = "UNSTAKE_TYPE_UNSPECIFIED"
    UNSTAKE_TYPE_PARTIAL = "UNSTAKE_TYPE_PARTIAL"
    UNSTAKE_TYPE_FULL = "UNSTAKE_TYPE_FULL"


class StakeType(Enum):
    STAKE_TYPE_UNSPECIFIED = "STAKE_TYPE_UNSPECIFIED"
    STAKE_TYPE_INITIAL_DEPOSIT = "STAKE_TYPE_INITIAL_DEPOSIT"
    STAKE_TYPE_TOP_UP = "STAKE_TYPE_TOP_UP"


class XMLiquidationStatus(Enum):
    XM_LIQUIDATION_STATUS_UNSET = "XM_LIQUIDATION_STATUS_UNSET"
    XM_LIQUIDATION_STATUS_PRE_LIQUIDATION = "XM_LIQUIDATION_STATUS_PRE_LIQUIDATION"
    XM_LIQUIDATION_STATUS_LIQUIDATING = "XM_LIQUIDATION_STATUS_LIQUIDATING"
    XM_LIQUIDATION_STATUS_LIQUIDATED = "XM_LIQUIDATION_STATUS_LIQUIDATED"
    XM_LIQUIDATION_STATUS_CANCELED = "XM_LIQUIDATION_STATUS_CANCELED"
    XM_LIQUIDATION_STATUS_FAILED = "XM_LIQUIDATION_STATUS_FAILED"


class PrimeXMControlStatus(Enum):
    CONTROL_STATUS_TRADES_AND_WITHDRAWALS = "CONTROL_STATUS_TRADES_AND_WITHDRAWALS"
    CONTROL_STATUS_TRADES_ONLY = "CONTROL_STATUS_TRADES_ONLY"
    CONTROL_STATUS_SESSION_LOCKED = "CONTROL_STATUS_SESSION_LOCKED"


class PrimeXMMarginLevel(Enum):
    MARGIN_LEVEL_HEALTHY = "MARGIN_LEVEL_HEALTHY"
    MARGIN_LEVEL_WARNING = "MARGIN_LEVEL_WARNING"
    MARGIN_LEVEL_CRITICAL = "MARGIN_LEVEL_CRITICAL"
    MARGIN_LEVEL_SUSPENSION = "MARGIN_LEVEL_SUSPENSION"
    MARGIN_LEVEL_LIQUIDATION = "MARGIN_LEVEL_LIQUIDATION"
    MARGIN_LEVEL_DEFICIT = "MARGIN_LEVEL_DEFICIT"
    MARGIN_LEVEL_RESTRICTED = "MARGIN_LEVEL_RESTRICTED"


class PrimeXMMarginRequirementType(Enum):
    MARGIN_REQUIREMENT_TYPE_UNSPECIFIED = "MARGIN_REQUIREMENT_TYPE_UNSPECIFIED"
    MARGIN_REQUIREMENT_TYPE_DMR_PLUS_PMR = "MARGIN_REQUIREMENT_TYPE_DMR_PLUS_PMR"
    MARGIN_REQUIREMENT_TYPE_IPMR_PLUS_IFMR = "MARGIN_REQUIREMENT_TYPE_IPMR_PLUS_IFMR"


class PrimeXMHealthStatus(Enum):
    HEALTH_STATUS_HEALTHY = "HEALTH_STATUS_HEALTHY"
    HEALTH_STATUS_WARNING = "HEALTH_STATUS_WARNING"
    HEALTH_STATUS_CRITICAL = "HEALTH_STATUS_CRITICAL"
    HEALTH_STATUS_SUSPENDED = "HEALTH_STATUS_SUSPENDED"
    HEALTH_STATUS_RESTRICTED = "HEALTH_STATUS_RESTRICTED"
    HEALTH_STATUS_PRE_LIQUIDATION = "HEALTH_STATUS_PRE_LIQUIDATION"
    HEALTH_STATUS_LIQUIDATING = "HEALTH_STATUS_LIQUIDATING"
    HEALTH_STATUS_IN_DEFICIT = "HEALTH_STATUS_IN_DEFICIT"


class PrimeXMMarginThresholdType(Enum):
    MARGIN_THRESHOLD_TYPE_UNSPECIFIED = "MARGIN_THRESHOLD_TYPE_UNSPECIFIED"
    MARGIN_THRESHOLD_EQUITY_RATIO = "MARGIN_THRESHOLD_EQUITY_RATIO"
    MARGIN_THRESHOLD_DEFICIT_RATIO = "MARGIN_THRESHOLD_DEFICIT_RATIO"
    MARGIN_THRESHOLD_NONE = "MARGIN_THRESHOLD_NONE"


class RewardSubtype(Enum):
    MEV_REWARD = "MEV_REWARD"
    INFLATION_REWARD = "INFLATION_REWARD"
    BLOCK_REWARD = "BLOCK_REWARD"
    VALIDATOR_REWARD = "VALIDATOR_REWARD"
    TRANSACTION_REWARD = "TRANSACTION_REWARD"
    STAKING_FEE_REBATE_REWARD = "STAKING_FEE_REBATE_REWARD"
    BUIDL_DIVIDEND = "BUIDL_DIVIDEND"
    CUSTOM_STABLECOIN_REWARD = "CUSTOM_STABLECOIN_REWARD"


class ValidatorProvider(Enum):
    VALIDATOR_PROVIDER_COINBASE_CLOUD = "VALIDATOR_PROVIDER_COINBASE_CLOUD"
    VALIDATOR_PROVIDER_MAVAN = "VALIDATOR_PROVIDER_MAVAN"
    VALIDATOR_PROVIDER_FIGMENT = "VALIDATOR_PROVIDER_FIGMENT"
    VALIDATOR_PROVIDER_CODEFI = "VALIDATOR_PROVIDER_CODEFI"
    VALIDATOR_PROVIDER_ATTESTANT = "VALIDATOR_PROVIDER_ATTESTANT"
    VALIDATOR_PROVIDER_GALAXY = "VALIDATOR_PROVIDER_GALAXY"


class TransactionType(Enum):
    DEPOSIT = "DEPOSIT"
    WITHDRAWAL = "WITHDRAWAL"
    INTERNAL_DEPOSIT = "INTERNAL_DEPOSIT"
    INTERNAL_WITHDRAWAL = "INTERNAL_WITHDRAWAL"
    SWEEP_DEPOSIT = "SWEEP_DEPOSIT"
    SWEEP_WITHDRAWAL = "SWEEP_WITHDRAWAL"
    PROXY_DEPOSIT = "PROXY_DEPOSIT"
    PROXY_WITHDRAWAL = "PROXY_WITHDRAWAL"
    BILLING_WITHDRAWAL = "BILLING_WITHDRAWAL"
    REWARD = "REWARD"
    COINBASE_REFUND = "COINBASE_REFUND"
    TRANSACTION_TYPE_OTHER = "TRANSACTION_TYPE_OTHER"
    WITHDRAWAL_ADJUSTMENT = "WITHDRAWAL_ADJUSTMENT"
    DEPOSIT_ADJUSTMENT = "DEPOSIT_ADJUSTMENT"
    KEY_REGISTRATION = "KEY_REGISTRATION"
    DELEGATION = "DELEGATION"
    UNDELEGATION = "UNDELEGATION"
    RESTAKE = "RESTAKE"
    COMPLETE_UNBONDING = "COMPLETE_UNBONDING"
    WITHDRAW_UNBONDED = "WITHDRAW_UNBONDED"
    STAKE_ACCOUNT_CREATE = "STAKE_ACCOUNT_CREATE"
    CHANGE_VALIDATOR = "CHANGE_VALIDATOR"
    STAKE = "STAKE"
    UNSTAKE = "UNSTAKE"
    REMOVE_AUTHORIZED_PARTY = "REMOVE_AUTHORIZED_PARTY"
    STAKE_AUTHORIZE_WITH_SEED = "STAKE_AUTHORIZE_WITH_SEED"
    SLASH = "SLASH"
    COINBASE_DEPOSIT = "COINBASE_DEPOSIT"
    CONVERSION = "CONVERSION"
    CLAIM_REWARDS = "CLAIM_REWARDS"
    VOTE_AUTHORIZE = "VOTE_AUTHORIZE"
    WEB3_TRANSACTION = "WEB3_TRANSACTION"
    ONCHAIN_TRANSACTION = "ONCHAIN_TRANSACTION"
    PORTFOLIO_STAKE = "PORTFOLIO_STAKE"
    PORTFOLIO_UNSTAKE = "PORTFOLIO_UNSTAKE"
    MERGE_STAKE = "MERGE_STAKE"


class ProductType(Enum):
    SPOT = "SPOT"
    FUTURE = "FUTURE"
    OPTION = "OPTION"


class DerivativeProductType(Enum):
    DERIVATIVE_PRODUCT_TYPE_SPOT = "DERIVATIVE_PRODUCT_TYPE_SPOT"
    DERIVATIVE_PRODUCT_TYPE_FUTURE = "DERIVATIVE_PRODUCT_TYPE_FUTURE"
    DERIVATIVE_PRODUCT_TYPE_EQUITY = "DERIVATIVE_PRODUCT_TYPE_EQUITY"
    DERIVATIVE_PRODUCT_TYPE_PREDICTION_MARKET = (
        "DERIVATIVE_PRODUCT_TYPE_PREDICTION_MARKET"
    )
    DERIVATIVE_PRODUCT_TYPE_OPTION = "DERIVATIVE_PRODUCT_TYPE_OPTION"
    DERIVATIVE_PRODUCT_TYPE_BASIS = "DERIVATIVE_PRODUCT_TYPE_BASIS"
    DERIVATIVE_PRODUCT_TYPE_EQUITY_OPTION = "DERIVATIVE_PRODUCT_TYPE_EQUITY_OPTION"
    DERIVATIVE_PRODUCT_TYPE_FUTURE_COMBO = "DERIVATIVE_PRODUCT_TYPE_FUTURE_COMBO"
    DERIVATIVE_PRODUCT_TYPE_OPTION_COMBO = "DERIVATIVE_PRODUCT_TYPE_OPTION_COMBO"


class OptionType(Enum):
    OPTION_TYPE_CALL = "OPTION_TYPE_CALL"
    OPTION_TYPE_PUT = "OPTION_TYPE_PUT"


class FcmMarginHealthState(Enum):
    FCM_MARGIN_HEALTH_STATE_HEALTHY = "FCM_MARGIN_HEALTH_STATE_HEALTHY"
    FCM_MARGIN_HEALTH_STATE_RESTRICTED = "FCM_MARGIN_HEALTH_STATE_RESTRICTED"
    FCM_MARGIN_HEALTH_STATE_PRE_LIQUIDATION = "FCM_MARGIN_HEALTH_STATE_PRE_LIQUIDATION"
    FCM_MARGIN_HEALTH_STATE_LIQUIDATION = "FCM_MARGIN_HEALTH_STATE_LIQUIDATION"
